---
kind: pipeline
type: docker
name: 部署博客

platform:
  os: linux
  arch: x86_64

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: 编译
    image: node:18.12.0
    commands:
      - yarn && yarn build
  - name: 复制到机器
    image: appleboy/drone-scp
    when:
      branch:
        - master
    settings:
      host: 10.10.10.5
      password:
        from_secret: password
      port: 22
      target: /www/wwwroot/blog.yiliaoliao.com
      source:
        - ./.vuepress/dist
  - name: 部署
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.10.10.5
      username: root
      password:
        from_secret: password
      port: 22
      command_timeout: 2m
      script:
        - cd /www/wwwroot/blog.yiliaoliao.com
        - rm -rf ./workspace
        - mv dist workspace
