name: Build and Deploy
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn && yarn build && yarn build:surge
          BUILD_DIR: .vuepress/dist/

      - name: deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'changero.surge.sh'
          project: '.vuepress/surge/'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
